---
- name: Pull Nexus Docker image
  docker_image:
    name: sonatype/nexus3
    source: pull

- name: Create Nexus data directory
  file:
    path: /srv/nexus
    state: directory
    mode: '0777'

- name: Run Nexus container
  docker_container:
    name: nexus
    image: sonatype/nexus3
    restart_policy: always
    ports:
      - "8081:8081"
    volumes:
      - "/srv/nexus:/nexus-data"
    networks:
      - name: interview_network