---
- name: Install Docker
  ansible.builtin.package:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started

- name: Create Docker network
  docker_network:
    name: interview_network